import { Contact } from '.';
export const mockContacts:  Contact[] = [
    {
      'jid': 'userh1',
      'name': 'userh1',
      'uid' : '',
      'pdp' : '',
      'roomJid' : 'userh1',
      'unreadMessageCount': 10,
      'status': 'online',
      'currentMessageContent' : 'message recente de user h1',
      'currentMessageRelativeDate': 'aujourd\'hui',
      'currentMessageTimestamp' : (new Date()),
      'defaultpdp' : 'profil-default.png',
      vEtes : null,
      isTyping : false

    },
    {
      'jid': 'userh2',
      'name': 'nom un peu plus long',
      'uid' : '',
      'pdp' : '',
      'roomJid' : 'userh1',
      'unreadMessageCount': 5,
      'status': 'online',
      'currentMessageContent' : 'message recente de user h2',
      'currentMessageRelativeDate': 'aujourd\'hui',
      'currentMessageTimestamp' : (new Date()),
      'defaultpdp' : 'profil-default.png',
      vEtes : null,
      isTyping : false
    },
    {
      'jid': 'userh3',
      'name': 'userh3',
      'uid' : '',
      'pdp' : '',
      'roomJid' : 'userh1',
      'unreadMessageCount': 3,
      'status': 'online',
      'currentMessageContent' : 'message recente de user h2',
      'currentMessageRelativeDate': 'aujourd\'hui',
      'currentMessageTimestamp' : (new Date()),
      'defaultpdp' : 'profil-default.png',
      vEtes : null,
      isTyping : false
    },
    {
      'jid': 'userh4',
      'name': 'userh4',
      'uid' : '',
      'pdp' : '',
      'roomJid' : 'userh1',
      'unreadMessageCount': 3,
      'status': 'online',
      'currentMessageContent' : 'message recente de user h2',
      'currentMessageRelativeDate': 'aujourd\'hui',
      'currentMessageTimestamp' : (new Date()),
      'defaultpdp' : 'profil-default.png',
      vEtes : null,
      isTyping : false
    },
    {
      'jid': 'userh5',
      'name': 'userh5',
      'uid' : '',
      'pdp' : '',
      'roomJid' : 'userh1',
      'unreadMessageCount': 3,
      'status': 'online',
      'currentMessageContent' : 'message recente de user h2',
      'currentMessageRelativeDate': 'aujourd\'hui',
      'currentMessageTimestamp' : (new Date()),
      'defaultpdp' : 'profil-default.png',
      vEtes : null,
      isTyping : false
    },
    {
      'jid': 'userh6',
      'name': 'userh6',
      'uid' : '',
      'pdp' : '',
      'roomJid' : 'userh1',
      'unreadMessageCount': 3,
      'status': 'online',
      'currentMessageContent' : 'message recente de user h2',
      'currentMessageRelativeDate': 'aujourd\'hui',
      'currentMessageTimestamp' : (new Date()),
      'defaultpdp' : 'profil-default.png',
      vEtes : null,
      isTyping : false
    }
  ];
