export const mockcity: any =  {
    "took":168,
    "timed_out":false,
    "_shards":{
        "total":3,
        "successful":3,
        "failed":0
    },
    "hits":{
        "total":176,
        "max_score":1.0,
        "hits":[
            {
                "_index":"france",
                "_type":"ville",
                "_id":"AVzLc7iq6BMeNFXo7Vbc",
                "_score":1.0,
                "_source":{
                    "cp":75008,
                    "commune":"PARIS-8E-ARRONDISSEMENT",
                    "departement":"PARIS",
                    "region":"ILE-DE-FRANCE",
                    "statut":"Chef-lieu canton",
                    "geo_point_2d":{
                        "lat":48.8725272666,
                        "lon":2.31258256042
                    }
                }
            },
            {
                "_index":"france",
                "_type":"ville",
                "_id":"AVzLdL3h6BMeNFXo7V7W",
                "_score":1.0,
                "_source":{
                    "cp":23140,
                    "commune":"PARSAC",
                    "departement":"CREUSE",
                    "region":"LIMOUSIN",
                    "statut":"Commune simple",
                    "geo_point_2d":{
                        "lat":46.1973815424,
                        "lon":2.1397496521
                    }
                }
            },
            {
                "_index":"france",
                "_type":"ville",
                "_id":"AVzLdL3h6BMeNFXo7V7k",
                "_score":1.0,
                "_source":{
                    "cp":19200,
                    "commune":"SAINT-PARDOUX-LE-NEUF",
                    "departement":"CORREZE",
                    "region":"LIMOUSIN",
                    "statut":"Commune simple",
                    "geo_point_2d":{
                        "lat":45.6127807921,
                        "lon":2.33140885442
                    }
                }
            },
            {
                "_index":"france",
                "_type":"ville",
                "_id":"AVzLdHrg6BMeNFXo7VzO",
                "_score":1.0,
                "_source":{
                    "cp":42120,
                    "commune":"PARIGNY",
                    "departement":"LOIRE",
                    "region":"RHONE-ALPES",
                    "statut":"Commune simple",
                    "geo_point_2d":{
                        "lat":45.9876941251,
                        "lon":4.09212986006
                    }
                }
            },
            {
                "_index":"france",
                "_type":"ville",
                "_id":"AVzLdfaR6BMeNFXo7WVi",
                "_score":1.0,
                "_source":{
                    "cp":2160,
                    "commune":"PARGNAN",
                    "departement":"AISNE",
                    "region":"PICARDIE",
                    "statut":"Commune simple",
                    "geo_point_2d":{
                        "lat":49.3942391486,
                        "lon":3.70308940891
                    }
                }
            },
            {
                "_index":"france",
                "_type":"ville",
                "_id":"AVzLda8k6BMeNFXo7WPN",
                "_score":1.0,
                "_source":{
                    "cp":40090,
                    "commune":"UCHACQ-ET-PARENTIS",
                    "departement":"LANDES",
                    "region":"AQUITAINE",
                    "statut":"Commune simple",
                    "geo_point_2d":{
                        "lat":43.945851007,
                        "lon":-0.548232922366
                    }
                }
            },
            {
                "_index":"france",
                "_type":"ville",
                "_id":"AVzLdylK6BMeNFXo7Wy_",
                "_score":1.0,
                "_source":{
                    "cp":48150,
                    "commune":"HURES-LA-PARADE",
                    "departement":"LOZERE",
                    "region":"LANGUEDOC-ROUSSILLON",
                    "statut":"Commune simple",
                    "geo_point_2d":{
                        "lat":44.2477855743,
                        "lon":3.38671686597
                    }
                }
            },
            {
                "_index":"france",
                "_type":"ville",
                "_id":"AVzLeDu46BMeNFXo7XRu",
                "_score":1.0,
                "_source":{
                    "cp":10100,
                    "commune":"PARS-LES-ROMILLY",
                    "departement":"AUBE",
                    "region":"CHAMPAGNE-ARDENNE",
                    "statut":"Commune simple",
                    "geo_point_2d":{
                        "lat":48.4812645725,
                        "lon":3.72853000882
                    }
                }
            },
            {
                "_index":"france",
                "_type":"ville",
                "_id":"AVzLeHxz6BMeNFXo7XXU",
                "_score":1.0,
                "_source":{
                    "cp":14310,
                    "commune":"PARFOURU-SUR-ODON",
                    "departement":"CALVADOS",
                    "region":"BASSE-NORMANDIE",
                    "statut":"Commune simple",
                    "geo_point_2d":{
                        "lat":49.0889824331,
                        "lon":-0.608826965285
                    }
                }
            },
            {
                "_index":"france",
                "_type":"ville",
                "_id":"AVzLeNZx6BMeNFXo7Xe5",
                "_score":1.0,
                "_source":{
                    "cp":20279,
                    "commune":"VILLE-DI-PARASO",
                    "departement":"HAUTE-CORSE",
                    "region":"CORSE",
                    "statut":"Commune simple",
                    "geo_point_2d":{
                        "lat":42.5826432898,
                        "lon":8.99012410909
                    }
                }
            }
            ]
        }
    }